context_data ={
        #Podstawowe informacje
         'logo': '',
         'issuer': ' Mikita Kharko',
         'phone_issuer' : '+48546654543',
         'email_issuer': ' m.kharko@nova-tracking.com',
         'branch_issuer' : 'NOVA TRACKING SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ /o. Warszawa',
         'nip':'PL9532641810',
         'city' : 'Warsaw',
         'date' : '04.01.2024',
         #tytuł dokumentu
         'document_type' : 'Zlecenie transportowe',
         'shipment_number' : 'NOV/009938/23/4',
         'info_about_invoice': 'Proszę podać na fakturze nr zlecenia',
         #dane przewoźnika
         'carrier':'Nova Tracking Sp. z o.o.',
         'carrier_address' :'ul. Zagrodnicza 20, 61-654 Poznań',
         'carrier_nip' :' 9532641810',
         'contact_person' : ['Jakub Malinowski' , 'Marcin Hajdul'], #może być array
         #dane dla rfdWaybill carrier
         'carrier_street':'ul. Zagrodnicza 20',
         'carrier_postal_code':'61-654',
         'carrier_city':'Poznań',
         'carrier_licension_nr':'3332221233',
         #srodek transportu
         'truck':'DW123454',
         'trailer' :'DW345444',
         'vehicle_type' : '',
         'driver':'Marek Kowalski',
         'driver_id_card':'',
         'driver_passport':'ABC123456',
         'driver_phone':'604104102',
         #points for rfw shipping instruction
         'poi_points' : [
             {
                'name': 'FIRMA OPONIARSKA TC DĘBICA S.A.',
                'street':'1 Maja',
                'building_nr': '1',
                'country_code': 'PL',
                'postal_code': '39-208',
                'city': 'Dębica',
                'country': 'Polska',
                'open_hour': '09:00',
                'close_hour': '18:00',
                'date' : '2023-10-09, 08:00',
                #dla rfdWaybill  poistart
                'start_date':'2023-10-09 08:00',
                ######
                #cała lista ładunków dla poszczególnych punktów
                'PoiLoad' : [
                    {
                        'CBM' : '242',
                        'name': 'Buty',
                        'quantity':'450',
                        'weight_brutto':'24000',
                        'length' : '23',
                        'height': '43',
                        'width': '32',
                        'type': 'pallets',
                        'info': '',
                        'total_weight' : '48000',
                    },
                    {
                        'CBM' : '',
                        'name': 'Kwiaty',
                        'quantity':'450',
                        'weight_brutto':'24000',
                        'length' : '23',
                        'height': '43',
                        'width': '32',
                        'type': 'pallets',
                        'info': 'Testowe uwagi do ładunku',
                        'dimensions': '',
                        'total_weight': '48000',
                    },
                    ],
                'PoiCustom':[
                    {
                        'CBM' : '242',
                        'name': 'Buty',
                        'quantity':'450',
                        'weight_brutto':'24000',
                        'length' : '23',
                        'height': '43',
                        'width': '32',
                        'type': 'pallets',
                        'info': '',
                        'total_weight' : '48000', 
                    }
                ],
                'PoiUnload' :[],
                'PoiOpenT1':[],
                'PoiPortOut':[],
                'PoiDocumentReciept':[],
                'PoiEmptyRoad':[],
                'PoiUnloadEmpty':[],
                'PoiLoadFull':[],
                'PoiUnloadFull':[],
                'ref_number' : 'CDSA4562311',
                'contact_person' : 'Bartosz',
                'contact_person_phone' : '6785334322',
                'info':'Po zaladunku odprawa adres sms\n ttt  weer'
             },
             {
                'name': 'Mahle Behr Ostrow Wielkopolski Sp.',
                'street':'Wodna',
                'building_nr': '15',
                'country_code': 'PL',
                'postal_code': '63-400',
                'city': 'Ostrów Wielkopolski',
                'country': 'Polska',
                'open_hour': '09',
                'close_hour': '18',
                'date' : '2023-10-10, 10:00',
                #dla rfdWaybill  poistart
                'start_date':'2023-10-10 10:00',
                #####
                'PoiLoad' : [],
                'PoiCustom':[],
                'PoiUnload' :[
                       {
                        'CBM' : '242',
                        'name': 'Buty',
                        'quantity':'450',
                        'weight_brutto':'24000',
                        'length' : '23',
                        'height': '43',
                        'width': '32',
                        'type': 'pallets',
                        'info': '',
                        'total_weight' : '48000',
                    },
                    {
                        'CBM' : '',
                        'name': 'Kwiaty',
                        'quantity':'450',
                        'weight_brutto':'24000',
                        'length' : '23',
                        'height': '43',
                        'width': '32',
                        'type': 'pallets',
                        'info': 'Testowe uwagi do ładunku',
                        'dimensions': '',
                        'total_weight': '48000',
                    },
                ],
                'PoiOpenT1':[],
                'PoiPortOut':[],
                'PoiDocumentReciept':[],
                'PoiEmptyRoad':[],
                'PoiUnloadEmpty':[],
                'PoiLoadFull':[],
                'PoiUnloadFull':[],
                'ref_number' : 'CDSA4562311',
                'contact_person' : 'Adam Nowak',
                'contact_person_phone' : '6785554322',
                'info':'Załadunek rampa 23'
             }
         ],
         #cargo
         'dict_cargo' : {
            'Załadunek' : 'PoiLoad',
            'Odprawa':'PoiCustom',
            'Rozładunek': 'PoiUnload',
            'Otwarcie T1': 'PoiOpenT1',
            'FieldPortOut' : 'PoiPortOut',
            'Odbiór dokumentów':'PoiDocumentReciept',
            'Podjęcie pusty':'PoiEmptyRoad',
            'Złożenie pusty' : 'PoiUnloadEmpty',
            'Podjęcie pełny' : 'PoiLoadFull',
            'Złożenie pełny': 'PoiUnloadFull',
         },
         #dla rfd waybill są wybierane ładunki które mają typ LOAD
          'cargos': [
              {
                'CBM' : '242',
                'name': 'Buty',
                'quantity':'450',
                'weight_brutto':'24000',
                'length' : '23',
                'height': '43',
                'width': '32',
                'type': 'pallets',
                'info': '',
                'total_weight' : '48000',
              },
              {
                'CBM' : '',
                'name': 'Kwiaty',
                'quantity':'450',
                'weight_brutto':'24000',
                'length' : '23',
                'height': '43',
                'width': '32',
                'type': 'pallets',
                'info': 'Testowe uwagi do ładunku',
                'dimensions': '',
                'total_weight': '48000',
              }
          ],
         #payments
         "prefix_or_txt_arr":[],
         'fracht_txt_arr':["Fracht przewozowy 1200 PLN netto + VAT"],
         'payment_term_txt_arr':["Termin p\u0142atno\u015bci: 60 dni od daty wystawienia"],
         'fracht': '1200',
         'fracht_currency':'PLN',
         'payment_term':'Termin p\u0142atno\u015bci: 60 dni od daty wystawienia',
         'goods_value': 2300,
         'goods_value_currency' : 'EUR',
         'extra_cost' : 1200,
         'extra_cost_currency': 'EUR',
         'shipment_note': 'Notatka ogólna test',
         'shipment_internal_note' : 'Notatka wewnętrzna test\nZ nowej string',
         #Dane dla zlecnia LCL SEA
         #'pin': '3444533',
         #'ref_number':'TRSU1233',
         #'custom_type':'T1',
         #'custom_point': 'HERMES" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ \n Legionów 87, 81-413, Gdynia, PL',
         'pallets_return': '',
         'documents_return':'',
         'conditions': '',
         'conditions_rfd_waybill': '',
         'branch':{
             'phone':'',
             'fax':'',
             'email':'',
             'full_name':'NOVA TRACKING SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ /o. Warszawa',
             'street':'Aleje Jerozolimskie 33',
             'postal_code':'00-200',
             'city':'Warszawa'
         },
         'company_user':{
             'full_name':'Nova Tracking Sp. z o.o.',
             'phone':'',
             'fax':'',
             'nip': '9532641810' ,
             'regon':'34153695000000',
             'street':'ul Zagrodnicza 20',
             'postal_code':'61-654',
             'city':'Poznań'
             

         },

}